name: DiskANN Build Python Wheel
on:
  workflow_call:
    inputs:
      runner-os:
        required: true
        type: string
      python-version:
        required: true
        type: string
    jobs:
      build:
        name: Build for ${{inputs.python-version}} on ${{inputs.runner-os}}
        runs-on: ${{inputs.runner-os}}
        defaults:
          run:
            shell: bash
        steps:
          - name: Checkout repository
            uses: actions/checkout@v2
            with:
              submodules: true
          - uses: actions/setup-python@v3
          - name: Install cibuildwheel
            run: python -m pip install cibuildwheel==2.11.3
          - name: Building Wheel for Python ${{inputs.python-version}}
            run: python -m cibuildwheel --output-dir dist
            env:
              CIBW_BUILD: ${{ inputs.python-version }}
          - uses: actions/upload-artifact@v3
            with:
              name: wheels
              path: ./dist/*.whl
