name: DiskANN Pull Request Build and Test
on: [pull_request]
jobs:
  docker-container-build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v2
      - name: Docker build
        run: |
          docker build .
  build:
    name: DiskANN Build CLI Applications
    uses: ./.github/workflows/build-cli.yml
  data:
    name: Generate Random Test Data
    uses: ./.github/workflows/generate-random-test-data.yml
    needs: [build]
  acceptance:
    name: DiskANN Acceptance Tests
    uses: ./.github/workflows/acceptance-tests.yml
    needs: [build, data]
#  python:
#    name: DiskANN Build Python Wheel
#    uses: ./.github/workflows/build-python.yml
