name: DiskANN Pull Request Build and Test
on: [pull_request]
jobs:
  docker-container-build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v2
      - name: Docker build
        run: |
          docker build .
  build:
    uses: ./.github/workflows/components/build-cli.yml
  data:
    uses: ./.github/workflows/components/generate-random-test-data.yml
  acceptance:
    uses: ./.github/workflows/components/acceptance-tests.yml
  python:
    uses: ./.github/workflows/components/build-python.yml
