name: DiskANN Push Build
on: [push]
jobs:
  build:
    strategy:
      fail-fast: false
      matrix:
        os: [ ubuntu-latest, windows-2019, windows-latest ]
    name: Build for ${{matrix.os}}
    runs-on: ${{matrix.os}}
    defaults:
      run:
        shell: bash
    steps:
      - name: Checkout repository
        if: ${{ runner.os == 'Linux' }}
        uses: actions/checkout@v2
      - name: Checkout repository
        if: ${{ runner.os == 'Windows' }}
        uses: actions/checkout@v2
        with:
          submodules: true
      - run: |
          pwd
          ls -R .
        shell: bash
      - name: DiskANN Build CLI Applications
        uses: ./.github/actions/build
#  python:
#    name: DiskANN Build Python Wheel
#    uses: ./.github/workflows/build-python.yml
