name: DiskANN Push Build
on: [push]
jobs:
  build:
    strategy:
      fail-fast: false
      matrix:
        os: [ ubuntu-latest, windows-2019, windows-latest ]
    name: Build for ${{matrix.os}}
    runs-on: ${{matrix.os}}
    defaults:
      run:
        shell: bash
    steps:
      uses: ./.github/actions/build.yml
#  python:
#    name: DiskANN Build Python Wheel
#    uses: ./.github/workflows/build-python.yml
