name: DiskANN Push Build
on: [push]
jobs:
  build:
    name: DiskANN Build CLI Applications
    uses: ./.github/actions/build.yml
#  python:
#    name: DiskANN Build Python Wheel
#    uses: ./.github/workflows/build-python.yml
